### ISSUE TITLE
React missing? no plus button

### ISSUE THREAD

**Issue by fanckush** [wagtail/wagtail-condensedinlinepanel#48] opened 2018-07-13 20:13 UTC
Do I need to add react manually? The plus button doesnt appear and get some JS errors. The rich text editor in the inline snippets are missing too and a get some js errors in the console.

How should I add react to the cmd admin part?
![screen shot 2018-07-13 at 22 13 26](https://user-images.githubusercontent.com/6278713/42711906-ff2cb064-86e9-11e8-9e8c-5ffbd96bbefb.jpg)

**Comment by Adrian-Turjak** [comment] 2018-07-15 23:32
Fanckush, I think you are hitting two problem. First, the rich text editor changed in wagtail 2.0, and unless you clear your browser cache and reload you may not be correctly loading the js for the new one (I had that issue during a wagtail version upgrade on a site).

The second on, the plus button missing, is a bug. Although after some digging, the button isn't missing... it's just that the padding/positioning of the container for the panel is broken so the button is hidden behind the panel above it. I was able to make the button show up by adding `padding-top: 50px;` to the `condensed-inline-panel__ui-container` class. Although likely that's not the idea solution.

@kaedroho You know the css here better than me, can you confirm this issue and propose a better fix than just adding padding?

**Comment by Adrian-Turjak** [comment] 2018-07-15 23:54
Nevermind, I was wrong, richtext field is indeed broken with the panel. It doesn't load, and it throws an error. After posting that I realised I didn't have any places where I used richtext in a model with this panel, so I thought I'd confirm I wasn't saying nonsense.

So we have two bugs here that are probably unrelated:
- [ ]  Richtext fields are broken in the gui using this panel (likely due to the new editor)
- [ ] Main add button is present but hidden due to css issues

**Comment by Adrian-Turjak** [comment] 2018-07-16 01:29
I've put up a pull request that just replaces the margin with padding and now correctly shows the button while removing the odd issues the margin caused to panels above this one.

**Comment by jhrr** [comment] 2018-08-20 11:29
I can confirm the CSS issue here also.

**Comment by jhrr** [comment] 2018-08-24 14:12
I'm going to try and fix this richtext issue myself as the maintainer doesn't seem to be around. @Adrian-Turjak could you post the error you mention here so I can have a look?

**Comment by kaedroho** [comment] 2018-11-19 22:51
Rich text issue fixed in https://github.com/wagtail/wagtail-condensedinlinepanel/pull/56

Please give it a try and let me know if it works for you.

**Comment by kaedroho** [comment] 2018-11-20 10:19
This should all be fixed now in 0.5.2 (just uploaded to pypi). Thanks everyone for looking into these issues!

**Closed by kaedroho** 2018-11-20 10:19 UTC
